# Generated by Django 4.1.5 on 2023-02-21 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BusinessName',
            field=models.CharField(max_length=100, null=True, verbose_name='사업자명'),
        ),
        migrations.AddField(
            model_name='user',
            name='BusinessNumber',
            field=models.CharField(max_length=10, null=True, verbose_name='사업자등록번호'),
        ),
    ]
