# Generated by Django 4.1.5 on 2023-02-23 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_businessname_user_businessnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_email',
            field=models.EmailField(max_length=128, null=True, verbose_name='사용자이메일'),
        ),
    ]
